<a href="https://colab.research.google.com/github/ifrah123781/DecodeLabs-Project-1-Data-Cleaning/blob/main/DecodeLabs_Project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

STEP # 01: IMPORT PANDAS

In [5]:
import pandas as pd

STEP # 02 UPLOADING EXCEL FILE

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Dataset for Data Analytics.xlsx to Dataset for Data Analytics.xlsx

STEP # 04 READ THE EXCEL FILE

In [6]:
df = pd.read_excel("Dataset for Data Analytics.xlsx")

STEP # 05: LET'S SEE OUR DATA

In [7]:
df.head()    # it will show first 5 rows of data

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

STEP # 06: UNDERSTAND THE DATA STRUCTURE

In [8]:
df.shape

(1200, 14)

STEP # 07: NOW CHECK COLUMNS NAMES

In [9]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

STEP # 08: CHECK DATA TYPES

In [10]:
df.dtypes

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

STEP # 09: CHECK MISSING VALUES

In [11]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

STEP # 10: CHECK DUPLICATE ORDER IDs

In [12]:
df["OrderID"].duplicated().sum()

np.int64(0)

STEP # 11: CHECK DUPLICATE ROWS

In [13]:
df. duplicated().sum()

np.int64(0)

STEP # 12: IF DUPLICATES EXIST, DON'T DELETE THEM YET

In [14]:
df[df["OrderID"].duplicated(keep=False)]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

STEP # 13: CHECK THE DATE DATA TYPES

In [15]:
df["Date"].dtype

dtype('<M8[ns]')

STEP # 14: CHECK THE ACTUAL DATE VALUES

In [16]:
df["Date"].head(10)

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
5   2023-10-23
6   2025-06-17
7   2023-05-12
8   2025-04-02
9   2023-11-21
Name: Date, dtype: datetime64[ns]

STEP # 15: CHECK FOR INVALID DATES

In [18]:
pd.to_datetime(df["Date"], errors="coerce").isna().sum()

np.int64(0)

STEP # 16: CHECK THE DATE RANGE

In [19]:
df["Date"].min(), df["Date"].max()

(Timestamp('2023-01-01 00:00:00'), Timestamp('2025-06-30 00:00:00'))

STEP # 17: CHECK NUMERIC COLUMNS

In [20]:
df[["Quantity", "UnitPrice", "ItemsInCart", "TotalPrice"]].dtypes

Quantity         int64
UnitPrice      float64
ItemsInCart      int64
TotalPrice     float64
dtype: object

STEP # 18: CHECK FOR SUSPICIOUS NEGATIVE VALUES

In [21]:
df[["Quantity", "UnitPrice", "ItemsInCart", "TotalPrice"]].describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

STEP # 19: CHECK TEXT COLUMNS

In [22]:
df["Product"].unique()

array(['Monitor', 'Phone', 'Tablet', 'Chair', 'Printer', 'Laptop', 'Desk'],
      dtype=object)

STEP # 20: CHECK PAYMENT METHODS

In [23]:
df["PaymentMethod"].unique()

array(['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash'],
      dtype=object)

In [24]:
df["OrderStatus"].unique()

array(['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending'],
      dtype=object)

In [25]:
df["ReferralSource"].unique()

array(['Instagram', 'Referral', 'Email', 'Facebook', 'Google'],
      dtype=object)

STEP # 21: HANDLE MISSING VALUES PROPERLY

In [26]:
# STEP # 21A: view missing rows first

df[df['CouponCode'].isnull()].head(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,NaN,Email,268.56
15,ORD200015,2023-07-17,C39416,Printer,1,473.96,942 Main St,Cash,Delivered,TRK54930938,3,NaN,Google,473.96
17,ORD200017,2024-03-02,C60672,Tablet,1,423.40,382 Main St,Debit Card,Shipped,TRK11972116,3,NaN,Referral,423.40
21,ORD200021,2024-11-17,C99023,Monitor,4,342.95,569 Main St,Cash,Delivered,TRK52646983,6,NaN,Google,1371.80
26,ORD200026,2024-03-06,C21944,Laptop,5,59.55,296 Main St,Online,Delivered,TRK80276812,6,NaN,Referral,297.75
28,ORD200028,2023-11-21,C59823,Phone,4,160.07,568 Main St,Online,Pending,TRK65895539,5,NaN,Email,640.28
31,ORD200031,2023-06-30,C26445,Chair,3,500.08,996 Main St,Debit Card,Returned,TRK31229981,6,NaN,Facebook,1500.24
32,ORD200032,2023-05-01,C12388,Tablet,5,536.72,830 Main St,Cash,Delivered,TRK99261395,10,NaN,Email,2683.60
36,ORD200036,2025-05-08,C59337,Laptop,2,534.43,465 Main St,Debit Card,Pending,TRK50961250,5,NaN,Facebook,1068.86
42,ORD200042,2024-05-06,C28712,Printer,2,151.66,980 Main St,Cash,Cancelled,TRK40772558,6,NaN,Instagram,303.32

In [27]:
# STEP # 21B: replace missing coupon code

df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [28]:
# STEP # 21C: verify that missing values are gone

df["CouponCode"].isnull().sum()

np.int64(0)

In [29]:
# STEP # 21D: verify "No Coupon"

df["CouponCode"].value_counts()

CouponCode
FREESHIP     313
No Coupon    309
WINTER15     292
SAVE10       286
Name: count, dtype: int64

STEP # 22: CLEAN THE TEXT DATA

In [30]:
# STEP # 22A: check payment methods

df["PaymentMethod"].unique()

array(['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash'],
      dtype=object)

In [31]:
# STEP # 22B: check order status

df["OrderStatus"].unique()

array(['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending'],
      dtype=object)

In [32]:
# STEP # 22C: check refuse source

df["ReferralSource"].unique()

array(['Instagram', 'Referral', 'Email', 'Facebook', 'Google'],
      dtype=object)

In [33]:
# STEP # 22D: check product

df["Product"].value_counts()

Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64

STEP # 23: CHECK ALL TEXT COLUMNS FOR EXTRA SPACES

In [35]:
text_columns = ["Product", "PaymentMethod", "OrderStatus", "ReferralSource"]

for column in text_columns:
    print(f"\n{column}:")
    print(df[column].astype(str).str.contains(r"^\s|\s$", regex=True).sum())

Product:
0

PaymentMethod:
0

OrderStatus:
0

ReferralSource:
0

STEP # 24: CHECK MISSING VALUES AGAIN

In [36]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

STEP # 25: VALIDATE TOTALPRICE

In [37]:
df["CalculateTotal"] = df["Quantity"] * df["UnitPrice"]
df[["Quantity", "UnitPrice", "CalculateTotal"]].head(10)

   Quantity  UnitPrice  CalculateTotal
0         5     570.62         2853.10
1         2     151.35          302.70
2         5     550.68         2753.40
3         1     273.19          273.19
4         4     626.01         2504.04
5         2     245.86          491.72
6         1     664.42          664.42
7         5     149.55          747.75
8         2     134.28          268.56
9         4     509.38         2037.52

STEP # 26: FIND INCORRECT TOTAL PRICES

In [38]:
df["PriceDifference"] = df["TotalPrice"] - df["CalculateTotal"]
df["PriceDifference"].abs().gt(0.01).sum()

np.int64(0)

STEP # 27: CHECK NUMERIC DATA TYPES

In [39]:
numeric_columns = ["Quantity", "UnitPrice","ItemsInCart", "TotalPrice"]
df[numeric_columns].dtypes

Quantity         int64
UnitPrice      float64
ItemsInCart      int64
TotalPrice     float64
dtype: object

STEP # 28: CORRECT/ CONFIRM DATE FORMAT

In [40]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df["Date"].dtype

dtype('<M8[ns]')

STEP # 29: FINAL DATA CLEANING VALIDATION

In [41]:
print("Total Rows:", len(df))
print("Total Columns:", len(df.columns))
print("Missing Values:", df.isnull( ).sum().sum())
print("Duplicate Rows:", df.duplicated().sum())
print("Duplicate OrderIDs:", df["OrderID"].duplicated().sum())
print("Invalid Dates:", pd.to_datetime(df["Date"], errors="coerce").isna().sum())
print("Incorrect Total Prices:", df["PriceDifference"].abs().gt(0.01).sum())

Total Rows: 1200
Total Columns: 16
Missing Values: 0
Duplicate Rows: 0
Duplicate OrderIDs: 0
Invalid Dates: 0
Incorrect Total Prices: 0

STEP # 30: REMOVE TEMPORARY COLUMNS

In [42]:
df = df.drop(columns=["CalculateTotal", "PriceDifference"])
df.shape

(1200, 14)

STEP # 31: EXPORT THE CLEANED DATASET

In [43]:
df.to_excel("Cleaned_Data_Analyst.xlsx", index=False)

STEP # 32: DOWNLOAD THE CLEANED DATASET

In [44]:
from google.colab import files
files.download("Cleaned_Data_Analyst.xlsx")